In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from hidden_lake import HiddenLakeEnv, generate_random_map, add_visible
from utils import Qlearning, EpsilonGreedy, Experiment

In [3]:
EPISODES = 100000  # Total episodes
LEARNING_RATE = 0.8  # Learning rate
GAMMA = 0.95  # Discounting rate
EPSILON = 0.5  # Exploration probability
MAP_SIZE = 3  # Number of tiles of one side of the squared environment
ACTION_SIZE = 4  # Number of possible actions
HAZARD_P = 0.2  # Probability that square is hazadorous
SLIP_P = 0  # Probability of slipping on the ice

In [4]:
env = HiddenLakeEnv(map_size = MAP_SIZE, hazard_p = HAZARD_P, slip_p = SLIP_P)
learner = Qlearning(learning_rate = LEARNING_RATE, gamma = GAMMA, action_size = ACTION_SIZE )
explorer = EpsilonGreedy(epsilon = EPSILON)
experiment = Experiment(env, learner, explorer, EPISODES)
states, steps, rewards, actions, qtable = experiment.run()

In [5]:
for i in states[:10]:
    # print(np.array(i))
    # print()
    print(np.array(i)[0] + np.array(i)[1]*2 + np.array(i)[2]*3)
    print(list(zip(['D','R','U','L'], np.round(qtable[i],5))))
    print()

[[1. 3. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[('D', 0.71944), ('R', 0.0), ('U', 0.72599), ('L', 0.62921)]

[[0. 3. 0.]
 [1. 0. 0.]
 [2. 0. 0.]]
[('D', 1.0), ('R', 0.00143), ('U', 0.9025), ('L', 0.95)]

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[('D', 0.94627), ('R', 0.67571), ('U', 0.83585), ('L', 0.88893)]

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]
[('D', 0.84239), ('R', 0.88014), ('U', 0.81681), ('L', 0.85167)]

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
[('D', 0.93363), ('R', 0.82381), ('U', 0.81404), ('L', 0.8559)]

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]
[('D', 0.84239), ('R', 0.88014), ('U', 0.81681), ('L', 0.85167)]

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]
[('D', 0.84239), ('R', 0.88014), ('U', 0.81681), ('L', 0.85167)]

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
[('D', 0.93363), ('R', 0.82381), ('U', 0.81404), ('L', 0.8559)]

[[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 2.]]
[('D', 1.0), ('R', 0.95), ('U', 0.9025), ('L', 0.9025)]

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
[('D', 0.95), ('R', 0.95), ('U', 0.85737), ('L', 0.80393)]
