In [1]:
%cd ~/gymnasium-test/
%load_ext line_profiler
%load_ext memory_profiler
# %load_ext autoreload
# %autoreload 2

/home/n.saumik/gymnasium-test


In [2]:
import numpy as np
from tree import Tree, Forest

In [90]:
for loc in (2,):

    with np.printoptions(linewidth=300):

        for decisions in (3,):  # 3, 4:

            for skill in range(1, decisions + 1):

                f = Forest(decisions + 1, mode=f"normal-{loc}-0", start=0, stop=20000)

                n, d = f.trees[0].n, f.trees[0].depth

                X, Y = f.get_training_data(skill, leaf=True)

                reaches = X[:, n:].mean(axis=0) * d
                rewards = (X[:, :n] * X[:, n:] * d).mean(axis=0)

                print(f"decisions={decisions}, skill={skill}")
                print(reaches.round(3))
                print(rewards.round(2))
                print(rewards.sum())
                print()
            print("-" * 50)

decisions=3, skill=1
[1.    0.918 0.082 0.844 0.074 0.075 0.008 0.774 0.07  0.068 0.005 0.069 0.005 0.007 0.001]
[0.   1.95 0.11 1.78 0.1  0.16 0.01 1.65 0.1  0.14 0.01 0.15 0.01 0.01 0.  ]
6.169876396881445

decisions=3, skill=2
[1.    0.845 0.155 0.725 0.119 0.142 0.013 0.671 0.054 0.115 0.004 0.133 0.01  0.012 0.   ]
[0.   1.82 0.12 1.63 0.11 0.4  0.02 1.5  0.08 0.33 0.01 0.29 0.01 0.04 0.  ]
6.358971086358676

decisions=3, skill=3
[1.    0.81  0.19  0.694 0.116 0.173 0.018 0.648 0.046 0.112 0.003 0.166 0.007 0.017 0.   ]
[0.   1.75 0.12 1.55 0.11 0.46 0.02 1.51 0.07 0.33 0.01 0.45 0.01 0.06 0.  ]
6.45638714618786

--------------------------------------------------


In [78]:
(X[:, :n] * X[:, n:] * d).mean(axis=0).round(2)

array([-0.  ,  0.9 ,  0.18,  0.81,  0.18,  0.42,  0.09])

In [72]:
X[:, n:]

(50000, 31)

In [60]:
X

array([[ 0.12573022,  0.45574102, -0.13210486, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.12573022,  0.45574102, -0.13210486, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.12573022,  0.45574102, -0.13210486, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.43797961,  0.44619173, -0.13915941, ...,  0.        ,
         0.        ,  0.        ],
       [-0.43797961,  0.44619173, -0.13915941, ...,  0.        ,
         0.        ,  0.        ],
       [-0.43797961,  0.44619173, -0.13915941, ...,  0.        ,
         0.        ,  0.        ]])

In [45]:
X.shape

(40000, 30)

In [17]:
for seed in range(10):
    exp(
        seed=0,
        decisions=8,
        window=0,
        mode="risk-0.5",
        budget=2,
        skill=0,
        opt="adam",
        lr=1,
        patience=20,
        write=True,
        num_nodes=16,
        num_layers=1,
    )




Starting experiment: Seed-0 Depth-9 Skill-0


2024-09-17 01:17:02.621450: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-17 01:17:02.835376: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 43598 MB memory:  -> device: 0, name: NVIDIA A40, pci bus id: 0000:12:00.0, compute capability: 8.6


train data: 0 9 0 1.6398414270952344
made testing forest
made testing data
made testing tensor
test data: 0 9 0 0.16241534613072872
make model: 0 9 0 0.07656366471201181


Seed 0 Depth 9 Skill 0:   2%|▎                | 40/2000 [00:11<08:59,  3.63it/s]


deleting: 0 9 0 0.2848206181079149



Starting experiment: Seed-0 Depth-9 Skill-0
train data: 0 9 0 0.002558964304625988
made testing forest
made testing data
made testing tensor
test data: 0 9 0 0.1517009474337101
make model: 0 9 0 0.021731005981564522


Seed 0 Depth 9 Skill 0:   2%|▎                | 37/2000 [00:08<07:25,  4.41it/s]


deleting: 0 9 0 0.20503788255155087



Starting experiment: Seed-0 Depth-9 Skill-0
train data: 0 9 0 0.0018933508545160294
made testing forest
made testing data
made testing tensor
test data: 0 9 0 0.13905601017177105
make model: 0 9 0 0.023977658711373806


Seed 0 Depth 9 Skill 0:   2%|▍                | 48/2000 [00:10<07:17,  4.46it/s]


deleting: 0 9 0 0.18374915421009064



Starting experiment: Seed-0 Depth-9 Skill-0
train data: 0 9 0 0.001213928684592247
made testing forest
made testing data
made testing tensor
test data: 0 9 0 0.1146177751943469
make model: 0 9 0 0.01686226949095726


Seed 0 Depth 9 Skill 0:   2%|▍                | 49/2000 [00:12<08:17,  3.92it/s]


deleting: 0 9 0 0.25404800940304995



Starting experiment: Seed-0 Depth-9 Skill-0
train data: 0 9 0 0.002888290211558342
made testing forest
made testing data
made testing tensor
test data: 0 9 0 0.17879657074809074
make model: 0 9 0 0.020471561700105667


Seed 0 Depth 9 Skill 0:   2%|▎                | 33/2000 [00:06<06:35,  4.97it/s]


deleting: 0 9 0 0.17755306232720613



Starting experiment: Seed-0 Depth-9 Skill-0
train data: 0 9 0 0.0012585772201418877
made testing forest
made testing data
made testing tensor
test data: 0 9 0 0.11943481955677271
make model: 0 9 0 0.01711201388388872


Seed 0 Depth 9 Skill 0:   2%|▎                | 36/2000 [00:06<06:19,  5.17it/s]


deleting: 0 9 0 0.18953850027173758



Starting experiment: Seed-0 Depth-9 Skill-0
train data: 0 9 0 0.001087486743927002
made testing forest
made testing data
made testing tensor
test data: 0 9 0 0.1287540104240179
make model: 0 9 0 0.01901885401457548


Seed 0 Depth 9 Skill 0:   2%|▎                | 42/2000 [00:10<07:57,  4.10it/s]


deleting: 0 9 0 0.2871744194999337



Starting experiment: Seed-0 Depth-9 Skill-0
train data: 0 9 0 0.002478795126080513
made testing forest
made testing data
made testing tensor
test data: 0 9 0 0.18054589442908764
make model: 0 9 0 0.03026272915303707


Seed 0 Depth 9 Skill 0:   1%|▏                | 28/2000 [00:08<10:21,  3.17it/s]


deleting: 0 9 0 0.31834603659808636



Starting experiment: Seed-0 Depth-9 Skill-0
train data: 0 9 0 0.0019152220338582993
made testing forest
made testing data
made testing tensor
test data: 0 9 0 0.1798812709748745
make model: 0 9 0 0.044095851480960846


Seed 0 Depth 9 Skill 0:   2%|▎                | 39/2000 [00:11<09:45,  3.35it/s]


deleting: 0 9 0 0.2913878681138158



Starting experiment: Seed-0 Depth-9 Skill-0
train data: 0 9 0 0.0016693957149982452
made testing forest
made testing data
made testing tensor
test data: 0 9 0 0.17063403129577637
make model: 0 9 0 0.030776871368288994


Seed 0 Depth 9 Skill 0:   2%|▎                | 39/2000 [00:10<08:35,  3.81it/s]


deleting: 0 9 0 0.28764464147388935
